### ISSUE TITLE
Python logging only works by first initializing Neptune

### ISSUE THREAD

**Issue by JasperLinmans** [neptune-ml/neptune-client#104]
I've noticed that the python logging module only writes to Neptune's STDOUT channel when I initialize the Neptune experiment first. Like so:

```import logging
import sys
import neptune

neptune.init(project_qualified_name='test_project')
experiment = neptune.create_experiment(name='test')

logger = logging.getLogger()
logger.setLevel(logging.INFO)

handler = logging.StreamHandler(sys.stdout)
handler.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)

logger.info('Initializing experiment')

for i in range(5):
    experiment.send_metric('iter', i)
    
    logger.info('Iteration: {}'.format(i))

logger.info('Wrapping up experiment')

experiment.stop()
```

The STDOUT channel of my neptune experiment does not show output of the logger instance when initializing it the other way around:

```import logging
import sys
import neptune

logger = logging.getLogger()
logger.setLevel(logging.INFO)

handler = logging.StreamHandler(sys.stdout)
handler.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)

neptune.init(project_qualified_name='test_project')
experiment = neptune.create_experiment(name='test')

logger.info('Initializing experiment')

for i in range(5):
    experiment.send_metric('iter', i)
    
    logger.info('Iteration: {}'.format(i))

logger.info('Wrapping up experiment')

experiment.stop()
```

A solution to this, if possible, would benefit me in a project with a complicated sequence of class initializations.

**Comment by kamil-kaczmarek** [comment]
Hey @JasperLinmans,

Thanks for the the feedback. @lukasz-walkiewicz can you take a look at it?

Best,
Kamil

**Comment by lukasz-walkiewicz** [comment]
Hi @JasperLinmans,

neptune-client doesn't have any dedicated support for the python logging module yet and therefore the first solution is the best workaround for now.
I discussed with the team how to bring support for logging to the client and we think that the most convenient and flexible option would be to add a method to the experiment which would allow you to register a new handler, associated with the experiment. Something like:   
```python
...
logger = logging.getLogger()
...
experiment = neptune.create_experiment(name='test')
experiment.register_handler(logger)
logger.info('Initializing experiment')
...
```
What do you think? Would that work for you?

**Comment by JasperLinmans** [comment]
Yes, that would totally work for me!

**Comment by lukasz-walkiewicz** [comment]
@JasperLinmans The support for the python logging module was merged in #107. The API has changed slightly compared to the original proposal:
```
...
logger = logging.getLogger()
...
experiment = neptune.create_experiment(name='test', logger=logger)
logger.info('Initializing experiment')
...
```
Please upgrade neptune-client to the latest version (>= 0.2.15) to use it.

**Comment by JasperLinmans** [comment]
Works perfectly, thanks!

The API from the original proposal however also would have been applicable to existing experiments (useful when continuing experiments):

```
...
logger = logging.getLogger()
...
# Resume experiment
session = Session()
project = session.get_project(project_qualified_name='Test/project')
experiment = project.get_experiments(id=experiment_id)[0]
experiment.register_handler(logger)
logger.info('Continuing experiment')
...
```

This would partly solve #105. 

Is there still a way with the current version to also define the logger after initialization?

**Comment by kamil-kaczmarek** [comment]
@lukasz-walkiewicz can you help with that?

**Comment by lukasz-walkiewicz** [comment]
I'm afraid that's not possible right now. Currently, we support only a single immutable life cycle per experiment (you can create/start and stop an experiment only once) and a logger definition is a part of an experiment's execution context so it can't be defined later on. That being said, we noticed that this introduces unnecessary restrictions for users and we have plans to improve this mechanism in the near future.
