### ISSUE TITLE
How do I download from public neptune drive

### ISSUE THREAD

**Issue by choochtech** [neptune-ml/neptune-client#106]
Hi,

I am trying to download the /public/dsb_2018_data/  data on the public Neptune drive.   I can't find any sample code on downloading data from the Neptune public drive.  

Any help is very appreciated.

Thanks

**Comment by kamil-kaczmarek** [comment]
Hi @Hakan79,

Neptune `/public` directory is a part of previous Neptune instance (app.neptune.ml). We are going to close this instance on July 31st 2019. After that date public directory will not be available.

If you're still on the old instance I strongly recommend to move to the new one: ui.neptune.ml

In general, we do not provide methods to download data from `/public` directory. For now, you can use this data in your experiments while running them on the old instance. Here is more info about it: https://documentation.neptune.ml/how-to-guides/use-public-directory/

Hope this helps!

Best,
Kamil

**Comment by Hakan79** [comment]
Hi kamil-kaczmarek,

Thanks got it !

No problem. 

Thanks a lot 

Best

Hakan
