### ISSUE TITLE
set_property value is not string then silently doesn't set property

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ml/neptune-client#120]
I ran the following script:

```python
import neptune

neptune.init('jakub-czakon/examples')

with neptune.create_experiment():
    neptune.send_metric('score', 0.9)
    neptune.set_property('was_logged', True)
```
and no property is set for this experiment. There is no error it just doesn't send it.
But if I run the following with `str(True)`:

```python
import neptune

neptune.init('jakub-czakon/examples')

with neptune.create_experiment():
    neptune.send_metric('score', 0.9)
    neptune.set_property('was_logged', str(True))
```

Everything works just fine.
Maybe we should have an automated `str(value)` in `set_property()` or raise warnings or something.

**Comment by kamil-kaczmarek** [comment]
@aniezurawski does this still occurs?

**Comment by aniezurawski** [comment]
@kamil-kaczmarek Yes.

**Comment by kamil-kaczmarek** [comment]
thanks @aniezurawski let me plan to fix it :smile:

**Comment by aniezurawski** [comment]
This issue should not occur anymore since version 0.4.94.
