### ISSUE TITLE
create a silent flag in neptune

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ml/neptune-client#121]
I would like to be able to run scripts with neptune tracking but if I want to run it without tracking (for instance in tests) I want to have a flag that turns of neptune tracking.

Something like this would be great

```python
import neptune

SILENT=True

if SILENT:
   neptune.set_silent()

neptune.init()
neptune.create_experiemnt()
...
```

**Comment by d3sm0** [comment]
1up

**Comment by kamil-kaczmarek** [comment]
Thanks @d3sm0 :) Noted, coming soon...

**Comment by kamil-kaczmarek** [comment]
@d3sm0, I forgot to invite you to join https://spectrum.chat/neptune-community - we discuss feature requests, ideas and so on there!

**Comment by jakubczakon** [comment]
Thanks for adding it in #163
