### ISSUE TITLE
Default value of upload_source_files is None

### ISSUE THREAD

**Issue by dev7mt** [neptune-ml/neptune-client#175]
Hi,

the default value of `upload_source_files` in `create_experiment` is `None`, which is not an iterable. Therefore the following loop causes an error:
```
for filepath in upload_source_files:
            expanded_source_files |= set(glob.glob(filepath))
```
(line 391-392 in neptune/projects.py)

Running code with:
`project.create_experiment(name='foo', upload_source_files=[])`
does solve this problem, yet is not an elegant solution.

According to the doc-string, it is an optional argument:
`upload_source_files (:obj:`list`, optional, default is ``['main.py']``):`

Could you please fix this issue?

Thanks in advance!

**Comment by aniezurawski** [comment]
Hi, thanks for your report. We just released a fix. :)
