### ISSUE TITLE
Discovery of git repo location fails 

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ml/neptune-client#180]
In my settings the discovery of git repo location fails. Let me give the context: I have a main script where the experiment is defined but the execution of the experiment is made from a different script, which is outside my repo (to be precise, I run my experiments using ray). In such a context, the git repo of my experiment script is not located correctly. The problem is in:
```python
def discover_git_repo_location():
    import __main__

    if hasattr(__main__, '__file__'):
        return os.path.dirname(os.path.abspath(__main__.__file__))
    return None
```
which ask for the `__main__`, which, in my case, will be some external ray module. 

I would appreciate any workaround tips, e.g., how to change my  `__main__`.

Related to https://github.com/neptune-ml/neptune-contrib/issues/55

**Comment by pitercl** [comment]
Hi @wjaskowski ,

You can go with:
```python
import neptune

...

neptune.create_experiment(git_info=neptune.utils.get_git_info('/path/to/your/repo'))

```

We have it documented here: https://neptune-client.readthedocs.io/en/latest/technical_reference/utils.html

**Comment by wjaskowski** [comment]
Thx. This would be indeed a workaround for me. A small problem is that the git_info parameter is currently not exposed with NeptuneObserver for sacred but I can create my own.

**Comment by pitercl** [comment]
I'm closing this, let's track the progress on the NepttuneObserver issue in https://github.com/neptune-ml/neptune-contrib/issues/55.

**Comment by wjaskowski** [comment]
Sure but don't you think that `base_dir` and the dir where you look for git should be the same thing (at least by default)?

**Comment by pitercl** [comment]
@jakubczakon What do you think about this?

**Comment by jakubczakon** [comment]
@wjaskowski Thank you so much for your inputs and sorry for keeping you waiting.
Overall, I think there is a lot of good suggestions here and in the other thread. 
I am back in the office on Friday 4/10 and I will have updates on this then.

With that said, I agree, that it makes sense to have it as default and overall to have defaults that are not in any way surprising to Sacred users.

**Comment by jakubczakon** [comment]
It should be fixed now.
I actually went with the expected (for sacred users) `base_dir` handling.
Extended the proposed solution from https://github.com/neptune-ml/neptune-contrib/issues/55.
