### ISSUE TITLE
Http request to Neptune server failed: HTTPRequestTimeout().

### ISSUE THREAD

**Issue by Solacex** [neptune-ml/neptune-client#188]
![截屏2019-11-01上午11 17 27](https://user-images.githubusercontent.com/12868455/67994396-315ec100-fc99-11e9-83a0-cc73bfd45e5c.png)
It seems that I could not connect to neptune server.

**Comment by Solacex** [comment]
Sorry,  My server loses its connection to the Internet. 
Issue Closed.

**Comment by kamil-kaczmarek** [comment]
thanks @Solacex
