### ISSUE TITLE
experiment.get_system_properties() doesn't return "hostname"

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ml/neptune-client#193]
I think there is some regression. For recent experiments `experiment.get_properties()` return either an empty dictionary or `{'key1': 'value1', 'key2': '17', 'key3': 'other-value'}` (whatever that is) in case of the sandbox project.

For older experiments, I still can get the properties. 

This is probably a backend issue but there is no better place to put it.

**Comment by pitercl** [comment]
Hi @wjaskowski. I cannot reproduce it and the only place in our codebase I've been able to find, that has this `other-value` string, is our documentation.

Could you provide some way to reproduce this?

**Comment by wjaskowski** [comment]
Simply:
```python
import neptune
print(neptune.__version__)

proj = neptune.init('user/sandbox')
ex = proj.create_experiment(name='test1')
print(ex.get_properties())
ex.stop()
```
Output:
```bash
0.4.96
https://ui.neptune.ml/user/sandbox/e/SAN-150
{}
```

**Comment by wjaskowski** [comment]
I know that is going on. Previously I was using sacred's NeptuneObserver and properties such as `hostname` were filled in by sacred but now I use native neptune client and the dict is empty by default. My misunderstanding.

**Comment by wjaskowski** [comment]
OK. The real problem is that you don't expose `hostname` in the `get_system_properties`. A workaround:

```python
ex = proj.create_experiment(name='test1')
print(ex._backend.get_experiment(ex._internal_id))
```

**Comment by pitercl** [comment]
@wjaskowski, that's true, we don't expose it. I think this should be an easy fix, since this value is present in the experiment entity returned from backend. We'll do it soon. Thx!
