### ISSUE TITLE
Invalid JSON received from frontend.

### ISSUE THREAD

**Issue by zmonoid** [neptune-ml/neptune-client#69]
Got ```Invalid JSON received from frontend.``` message when login with ```neptune account login```. It may due to I am using socks proxy. Please kindly suggest a way to solve this problem.

I modified ```neptune/client.py``` file on func ``` def _upload_tar_data(self, experiment, api_method, data):``` to:
```python
         proxies = {"http": "socks5h://127.0.0.1:9999", 'https': 'socks5h://127.0.0.1:9999'}
         return session.send(session.prepare_request(request), proxies=proxies)
```

So that it works for neptune-client without command line.

**Comment by pitercl** [comment]
Hi @zmonoid,

From what I can see in our system, your account is bound to the newer version of Neptune, which relies solely on the `neptune-client` pip package and isn't compatible with `neptune-cli` (sorry for the confusion here!). This means, that you cannot use `neptune account login`, instead, you should rely on Python API from `neptune-client` and API Tokens

About using a proxy, we'll add it to our roadmap, but we're also happy to accept a PR :)

**Comment by zmonoid** [comment]
@pitercl 
Thanks for your answer.

Is there anyway we can still use ```neptune run --config cfg.yaml python main.py``` ?

**Comment by pitercl** [comment]
Right now the new library doesn't come with a feature-rich CLI - instead, we deviver (almost?) entire functionality via Python API. You can simply run

```bash
python main.py
```

and within your code write something like

```py
import neptune
with neptune.create_experiment(...) as exp:
    exp.send_metric(...)
    exp.send_text(...)
    ... etc.
```

Are you missing any particular features in the Python API?

**Comment by jakubczakon** [comment]
@zmonoid 

You can easily parse your cfg.yaml to the neptune config object.
There is a class that does just that in the neptune-contrib project.
Feel free to take it from [here](https://github.com/neptune-ml/neptune-contrib/blob/master/neptunecontrib/monitoring/notebooks.py#191-#233).

**Comment by zmonoid** [comment]
@pitercl @jakubczakon 
Thanks very much for your answer~
This is really a great project.
