### ISSUE TITLE
ability to change 'name', 'params' and 'description

### ISSUE THREAD

**Issue by kamil-kaczmarek** [neptune-ml/neptune-client#76]
Once I call `neptune.create_experiment()` is am unable to change: `name`, `params`, `description`.

I think that `neptune-client` should allow User to do it. My UC is that I want to append stuff to _params_ and assign _name_ and _description_ right before training loop.

What do you guys think?
@lukasz-walkiewicz @jakubczakon

**Comment by jakubczakon** [comment]
Well, to me params sort of define experiment and changing them/appending them during the experiment goes against it. I see how this would make code nicer in some situations. To marry both worlds I would suggest that we have an option to `.add_parameter` which cannot overwrite anything, but let's you add new params. @kamil-kaczmarek ?

When it comes to name and description it's a different story. It would make sense to me to append things to `description` during the experiment and have an autogenerated story passed to `description`.
The same story for `name` I think.

**Comment by kamil-kaczmarek** [comment]
no longer relevant
