### ISSUE TITLE
parameters are all strings

### ISSUE THREAD

**Issue by kamil-kaczmarek** [neptune-ml/neptune-client#77]
**Problem**
my code
```
PARAMS = {'lr': 0.0005,
          'dropout': 0.2,
          'batch_size': 64,
          'optimizer': 'adam',
          }

project = neptune.Session().get_project('kamil/Tensor-Cell-Demo')
npt_exp = project.create_experiment(name='neural-net-mnist',
                                    params=PARAMS
                                    )
```
Now, when I do: `npt_exp.get_parameters()['batch_size']`, I have string returned, while it should be int.

**Solution**
`npt_exp.get_parameters()` should return dict with original types.

What do you guys think: @pitercl @lukasz-walkiewicz

**Comment by aniezurawski** [comment]
Fixed in #79 .
