### ISSUE TITLE
Add option to download output/artifacts programatically

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ml/neptune-client#94]
It would be good to add an option to do something like this:

```python
...
experiment.get_output_files('my_model.h5', '/path/to/local/storage')
```
So that I could access (download) the artifacts from code.

**Comment by kamil-kaczmarek** [comment]
Hey,

Makes a lot of sense. So requirements are:
1. Experiment object has new method, `get_output_file(filename, destination_path)`
2. You simply download stuff from experiment output to local storage

@aniezurawski @pitercl Can we do it?

Best,
Kamil

**Comment by aniezurawski** [comment]
Done in https://github.com/neptune-ml/neptune-client/pull/98
